#!/bin/sh
f2py2e='python ../../f2py2e.py'

$f2py2e string.f -m sfoo -h sfoo.pyf --overwrite-signature --overwrite-makefile
gmake -f Makefile-sfoo clean sfoo

python -c '
import sfoo,Numeric
print sfoo.__doc__
sfoo.foo1("987654321","abcdefghij","ABC")
print "ok"
'
