#!/bin/sh

f2py2e='python ../../f2py2e.py'
$f2py2e array.f -m afoo -h afoo.pyf --overwrite-signature --overwrite-makefile
gmake -f Makefile-afoo clean afoo

python -c '
import afoo,Numeric
print afoo.__doc__

x=Numeric.array([-1,-2,-3,-4,-5])
w=Numeric.array([1.1,-0.2,-0.3,1,2])
print x,afoo.dfoo(x,w),x
print afoo.dfoo2([[12]])
print "ok"
'
