#!/bin/sh
f2py2e='python ../../f2py2e.py'

$f2py2e callbacktest.f -m cbfoo -h cbfoo.pyf --overwrite-signature --overwrite-makefile
F2PYFLAGS=--debug-capi2 gmake -f Makefile-cbfoo clean cbfoo

python -c '
import cbfoo,Numeric
print cbfoo.__doc__
def fun(x,y=2,z=3):
    print "Python:fun: x,y,z=",x,y,z
    print "Python:fun: 1+x,x=",1+x,x
    return 1+x,1-x,x
def strfun(x):
    ret = `34.567`
    print "Python:strfun: type(x)=",type(x)
    print "Python:strfun: x=",`x`
    print "Python:strfun: ret=",`ret`
    return ret
def arrfun(x,n=None):
    print "Python:arrfun: x=",`x`
    print "Python:arrfun: n=",`n`
    ret = 45+x
    #ret= (-241234,)
    x[0] = 79
    print "Python:arrfun: x=",`x`
    print "Python:arrfun: n=",`n`
    print "Python:arrfun: ret=",`ret`
    return ret
print cbfoo.foo(fun,1,(4,))
#print "cbfoo.zfoo(fun,1-1j,(4,))", "this is tested in test-site/b/runme_callback"
print cbfoo.strfoo.__doc__
print cbfoo.strfoo(strfun,"initINITinit")
print cbfoo.strfoo2(strfun,"initINITinit")
x=Numeric.array([[11,12],[13,14]],"D")
print cbfoo.arrfoo.__doc__
print x,"\n",cbfoo.arrfoo(arrfun,x),"\n",x
print "ok"
'
