#!/bin/sh
# $Revision: 1.6 $ $Date: 2000/04/26 14:09:32 $
# Pearu Peterson <pearu@ioc.ee>

f2py2e='python ../../f2py2e.py'

$f2py2e splines-smart.pyf \
    --overwrite-makefile -makefile -L/numeric/lib -lddierckx --use-libs
gmake -f Makefile-splines clean splines

python -c '\
from Numeric import array,zeros,asarray
import splines
print dir(splines)
from splines import *
print curfit.__doc__
x=array(range(10),"d")
y=x/2
print x
print "curfit(x,y)=",curfit(x,y)
print "ok"
'



