image: thomasjpfan/numpy-gitpod
tasks:
  # The base image complied numpy with ccache enabled. This second build
  # should be faster since it is using the cache.
  - init: python setup.py build_ext -i
  - openMode: split-right
    command: make -C doc -e SPHINXOPTS="-j auto" html

github:
  prebuilds:
    master: true
    branches: true
