extend-exclude = [
    "numpy/__config__.py",
    "numpy/distutils",
    "numpy/typing/_char_codes.py",
    "numpy/typing/tests/data",
    "spin/cmds.py",
    # Submodules.
    "doc/source/_static/scipy-mathjax",
    "vendored-meson/meson",
    "numpy/fft/pocketfft",
    "numpy/_core/src/umath/svml",
    "numpy/_core/src/npysort/x86-simd-sort",
    "numpy/_core/src/highway",
    "numpy/_core/src/common/pythoncapi-compat",
]

[lint]
preview = true
extend-select = [
    "B",
    "E",
    "W",
    "PGH",
    "PLE",
    "UP",
]
ignore = [
    "F",     # TODO: enable Pyflakes rules
    "B006",  # Do not use mutable data structures for argument defaults
    "B007",  # Loop control variable not used within loop body
    "B011",  # Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
    "B023",  # Function definition does not bind loop variable
    "B028",  # No explicit `stacklevel` keyword argument found
    "B904",  # Within an `except` clause distinguish raised exceptions from errors in exception handling
    "B905",  #`zip()` without an explicit `strict=` parameter
    "E241",
    "E251",
    "E265",
    "E266",
    "E302",
    "E402",
    "E501",  # TODO: Line too long
    "E712",
    "E721",
    "E731",
    "E741",
    "UP015", # Unnecessary mode argument
    "UP031", # TODO: Use format specifiers instead of percent format
]

[lint.per-file-ignores]
"test*.py" = ["B015", "B018", "E201", "E714"]
"bench_*.py" = ["B015", "B018"]
"_tempita.py" = ["B909"]
