#!/bin/sh
# $Revision: 1.3 $ $Date: 2000/01/21 21:01:59 $
# Pearu Peterson <pearu@ioc.ee>
PREFIX=`python -c "import sys;print sys.prefix"`
VERSION=`python -c "import sys;print sys.version[:3]"`
PYINC=$PREFIX/include/python$VERSION
GCCLIBDIR=`gcc -v 2>&1`
GCCLIBDIR=${GCCLIBDIR%/specs*}
GCCLIBDIR=${GCCLIBDIR#*from}
SO=so
FLAGS=-fPIC
test `uname` = "HP-UX" && SO=sl
cabase=cabase2
f2py2e=../../f2py2e.py
#rm -f $cabase-raw.f90
$f2py2e $cabase.f -h $cabase-raw.f90 -m cabase
$f2py2e $cabase-raw.f90 --debug-capi
test ! -e -cabase.o &&  g77 -c $FLAGS $cabase.f -o $cabase.o 
test ! -e -cabasemodule.o && gcc -c $FLAGS -I$PYINC cabasemodule.c 
test ! -e -cabasemodule.$SO && gcc -shared -o cabasemodule.$SO $FLAGS cabasemodule.o $cabase.o -L$GCCLIBDIR -lg2c

python -c '
from cabase import *
print cabase.__doc__
'
python $cabase.py

python -c 'print "ok"'