from typing import Final

import numpy as np

__version__: Final[str] = ...
_ilp64: Final[bool] = ...

###
# 1 -> 1

# (m,m) -> ()
det: Final[np.ufunc] = ...
# (m,m) -> (m)
cholesky_lo: Final[np.ufunc] = ...
cholesky_up: Final[np.ufunc] = ...
eigvals: Final[np.ufunc] = ...
eigvalsh_lo: Final[np.ufunc] = ...
eigvalsh_up: Final[np.ufunc] = ...
# (m,m) -> (m,m)
inv: Final[np.ufunc] = ...
# (m,n) -> (p)
qr_r_raw: Final[np.ufunc] = ...
svd: Final[np.ufunc] = ...

###
# 1 -> 2

# (m,m) -> (), ()
slogdet: Final[np.ufunc] = ...
# (m,m) -> (m), (m,m)
eig: Final[np.ufunc] = ...
eigh_lo: Final[np.ufunc] = ...
eigh_up: Final[np.ufunc] = ...

###
# 2 -> 1

# (m,n), (n) -> (m,m)
qr_complete: Final[np.ufunc] = ...
# (m,n), (k) -> (m,k)
qr_reduced: Final[np.ufunc] = ...
# (m,m), (m,n) -> (m,n)
solve: Final[np.ufunc] = ...
# (m,m), (m) -> (m)
solve1: Final[np.ufunc] = ...

###
# 1 -> 3

# (m,n) -> (m,m), (p), (n,n)
svd_f: Final[np.ufunc] = ...
# (m,n) -> (m,p), (p), (p,n)
svd_s: Final[np.ufunc] = ...

###
# 3 -> 4

# (m,n), (m,k), () -> (n,k), (k), (), (p)
lstsq: Final[np.ufunc] = ...
