[package.build]
source.path = "../.."
flags = ["freethreading"]

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.config]
extra-input-globs = ["**/*.c.src"]
compilers = ["c", "cxx"]
extra-args = ["-Csetup-args=-Dbuildtype=debug"]

[package.host-dependencies]
# FIXME https://github.com/numpy/numpy/issues/30478
# python = "*" prevents downstream from building cpython from sources.
# Workaround: fork numpy, then uncomment one of the following and
# comment out the other.

# Use latest cpython release from conda-forge
python-freethreading = "*"

# Use cpython git tip
# python.flags = ["freethreading"]
# python.git = "https://github.com/python/cpython"
# python.subdirectory = "Tools/pixi-packages"
# python.rev = "abdd7aea18bde039fe35983b5c0d8036bc16f1a7"  # v3.15.0a8

meson-python = "*"
cython = "*"
