# Last Change: Thu Jun 12 06:00 PM 2008 J
# vim:syntax=python
from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

env.NumpyPythonExtension('fftpack_lite',
                          source = ['fftpack_litemodule.c', 'fftpack.c'])
