#ifndef NUMPY_CORE_SRC_COMMON_NPY_CPU_DISPATCH_H_
#define NUMPY_CORE_SRC_COMMON_NPY_CPU_DISPATCH_H_
/**
 * This file is part of the NumPy CPU dispatcher.
 *
 * Please have a look at doc/reference/simd-optimizations.html
 * To get a better understanding of the mechanism behind it.
 */
#include "npy_cpu_features.h" // NPY_CPU_HAVE
#if (defined(__s390x__) || defined(__powerpc64__)) && !defined(__cplusplus) && defined(bool)
    /*
     * "altivec.h" header contains the definitions(bool, vector, pixel),
     * usually in c++ we undefine them after including the header.
     * It's better anyway to take them off and use built-in types(__vector, __pixel, __bool) instead,
     * since c99 supports bool variables which may lead to ambiguous errors.
     */
    // backup 'bool' before including 'npy_cpu_dispatch_config.h', since it may not defined as a compiler token.
    #define NPY__CPU_DISPATCH_GUARD_BOOL
    typedef bool npy__cpu_dispatch_guard_bool;
#endif
/**
 * Including the main configuration header 'npy_cpu_dispatch_config.h'.
 * This header is generated by the 'ccompiler_opt' distutils module and the Meson build system.
 *
 * For the distutils-generated version, it contains:
 *   - Headers for platform-specific instruction sets.
 *   - Feature #definitions, e.g. NPY_HAVE_AVX2.
 *   - Helper macros that encapsulate enabled features through user-defined build options
 *     '--cpu-baseline' and '--cpu-dispatch'. These options are essential for implementing
 *     attributes like `__cpu_baseline__` and `__cpu_dispatch__` in the NumPy module.
 *
 * For the Meson-generated version, it contains:
 *   - Headers for platform-specific instruction sets.
 *   - Helper macros that encapsulate enabled features through user-defined build options
 *     '--cpu-baseline' and '--cpu-dispatch'. These options remain crucial for implementing
 *     attributes like `__cpu_baseline__` and `__cpu_dispatch__` in the NumPy module.
 *   - Additional helper macros necessary for runtime dispatching.
 *
 * Note: In the Meson build, features #definitions are conveyed via compiler arguments.
 */
#include "npy_cpu_dispatch_config.h"
#ifndef NPY__CPU_MESON_BUILD
    // Define helper macros necessary for runtime dispatching for distutils.
    #include "npy_cpu_dispatch_distutils.h"
#endif
#if defined(NPY_HAVE_VSX) || defined(NPY_HAVE_VX)
    #undef bool
    #undef vector
    #undef pixel
    #ifdef NPY__CPU_DISPATCH_GUARD_BOOL
        #define bool npy__cpu_dispatch_guard_bool
        #undef NPY__CPU_DISPATCH_GUARD_BOOL
    #endif
#endif
#endif  // NUMPY_CORE_SRC_COMMON_NPY_CPU_DISPATCH_H_
