# vim:syntax=python
from numpy.distutils.scons import GetNumpyEnvironment
from numpy.distutils.scons.checkers.perflib import \
        CheckATLAS, CheckAccelerate, CheckMKL, CheckSunperf
from numpy.distutils.scons.checkers.custom_checkers import CheckCBLAS, CheckLAPACK
from numpy.distutils.scons import CheckF77Mangling

env = GetNumpyEnvironment(ARGUMENTS)

import os
try:
    os.environ['DEBUG_SCONS_CHECK']
    do_check = 1
except KeyError:
    do_check = 0

config = env.NumpyConfigure(custom_tests = 
    {'CheckATLAS' : CheckATLAS,
    'CheckMKL' : CheckMKL,
    'CheckAccelerate' : CheckAccelerate,
    'CheckCBLAS' : CheckCBLAS,
    'CheckLAPACK' : CheckLAPACK,
    'CheckF77Mangling' : CheckF77Mangling,
    'CheckSunperf' : CheckSunperf})

do_check = 1
if do_check:
    st, opts = config.CheckATLAS(autoadd = 0)
    st, opts = config.CheckMKL(autoadd = 0)
    st, opts = config.CheckAccelerate(autoadd = 0)
    st, opts = config.CheckSunperf(autoadd = 0)
    st = config.CheckCBLAS(autoadd = 0)
    st = config.CheckLAPACK(autoadd = 0)
    st = config.CheckF77Mangling()

    if env.has_key('LIBS'):
        print "LIBS of env is %s" % env.Dump('LIBS')
    else:
        print "No LIBS in env"

config.Finish()

