# vim:syntax=python
from numpy.distutils.scons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

config = env.Configure()
config.CheckHeader('stdio.h')
config.CheckLib('c', 'printf')
config.CheckLib('sndfile', 'sf_open')
config.Finish()

source = ['foo.c']
import sys
if sys.platform == 'win32':
    env.AppendUnique(CPPDEFINES = 'WIN32')
env.NumpyCTypes('foo', source)
