#!/bin/sh

f2py='python ../../f2py2e.py'

$f2py -m t -h t.pyf smgice.f --overwrite-signature
$f2py t.pyf

gmake -f Makefile-t

python -c '\
from Numeric import *
import t
x=zeros(1000)
y=ones(1000)
print x[:5],y[:5]
print t.icein(5,x,y,"t.data")
print x[:5],y[:5]
print "ok"
'