#ifndef NUMPY_CORE_SRC_MULTIARRAY_LEGACY_DTYPE_IMPLEMENTATION_H_
#define NUMPY_CORE_SRC_MULTIARRAY_LEGACY_DTYPE_IMPLEMENTATION_H_

NPY_NO_EXPORT npy_bool
PyArray_LegacyCanCastTypeTo(_PyArray_LegacyDescr *from, _PyArray_LegacyDescr *to,
        NPY_CASTING casting);

#endif  /* NUMPY_CORE_SRC_MULTIARRAY_LEGACY_DTYPE_IMPLEMENTATION_H_ */
