from typing import List

__all__: List[str]

class RankWarning(UserWarning): ...
class PolyError(Exception): ...
class PolyDomainError(PolyError): ...

# NOTE: Deprecated
# class PolyBase: ...

def trimseq(seq): ...
def as_series(alist, trim=...): ...
def trimcoef(c, tol=...): ...
def getdomain(x): ...
def mapparms(old, new): ...
def mapdomain(x, old, new): ...
