# undocumented internal testing module for ufunc features, defined in
# numpy/_core/src/umath/_umath_tests.c.src

from typing import Final, Literal as L, TypedDict, type_check_only

import numpy as np

@type_check_only
class _TestDispatchResult(TypedDict):
    func: str  # e.g. 'func_AVX2'
    var: str  # e.g. 'var_AVX2'
    func_xb: str  # e.g. 'func_AVX2'
    var_xb: str  # e.g. 'var_AVX2'
    all: list[str]  # e.g. ['func_AVX2', 'func_SSE41', 'func']

###

# undocumented
def test_signature(
    nin: int, nout: int, signature: str, /
) -> tuple[
    L[0, 1],  # core_enabled (0 for scalar ufunc; 1 for generalized ufunc)
    tuple[int, ...] | None,  # core_num_dims
    tuple[int, ...] | None,  # core_dim_ixs
    tuple[int, ...] | None,  # core_dim_flags
    tuple[int, ...] | None,  # core_dim_sizes
]: ...

# undocumented
def test_dispatch() -> _TestDispatchResult: ...

# undocumented test helpers for PyUFunc_ReplaceLoopBySignature
def replace_loop(ufunc: np.ufunc, /) -> object: ...
def restore_loop(ufunc: np.ufunc, capsule: object, /) -> None: ...
def create_unary_ufunc() -> np.ufunc: ...

# undocumented ufuncs and gufuncs
always_error: Final[np.ufunc] = ...
always_error_unary: Final[np.ufunc] = ...
always_error_gufunc: Final[np.ufunc] = ...
inner1d: Final[np.ufunc] = ...
innerwt: Final[np.ufunc] = ...
matrix_multiply: Final[np.ufunc] = ...
matmul: Final[np.ufunc] = ...
euclidean_pdist: Final[np.ufunc] = ...
cumsum: Final[np.ufunc] = ...
inner1d_no_doc: Final[np.ufunc] = ...
cross1d: Final[np.ufunc] = ...
_pickleable_module_global_ufunc: Final[np.ufunc] = ...  # 0->0 ufunc; segfaults if called
indexed_negative: Final[np.ufunc] = ...  # ntypes=0; can't be called
conv1d_full: Final[np.ufunc] = ...
