#include "common.c"

#include "hashdescr.c"
#include "numpyos.c"
#include "scalarapi.c"
#include "descriptor.c"
#include "flagsobject.c"
#include "ctors.c"
#include "iterators.c"
#include "mapping.c"
#include "number.c"
#include "getset.c"
#include "sequence.c"
#include "methods.c"
#include "convert_datatype.c"
#include "convert.c"
#include "shape.c"
#include "item_selection.c"
#include "calculation.c"
#include "usertypes.c"

#include "arraytypes.c"
#include "scalartypes.c"

#include "arrayobject.c"
#include "multiarraymodule.c"
