# Last Change: Thu Jun 12 06:00 PM 2008 J
# vim:syntax=python
from numscons import GetNumpyEnvironment, scons_get_paths

env = GetNumpyEnvironment(ARGUMENTS)
env.Append(CPPPATH = scons_get_paths(env['include_bootstrap']))
env.Append(CPPPATH = ['numpy'])

_capi = env.DistutilsPythonExtension('_capi', source = ['_capi.c'])
