# Last Change: Thu Jun 12 06:00 PM 2008 J
# vim:syntax=python
from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)
env.Append(CPPPATH = ['numpy'])

_capi = env.NumpyPythonExtension('_capi', source = ['_capi.c'])
