from collections.abc import Sequence
from typing import Any, overload

import numpy as np
from numpy import complexfloating
from numpy._typing import (
    NDArray,
    _ArrayLikeComplex_co,
    _ArrayLikeFloat_co,
    _ComplexLike_co,
    _FloatLike_co,
    _Shape,
)

__all__ = ["sqrt", "log", "log2", "logn", "log10", "power", "arccos", "arcsin", "arctanh"]

###

type _Array1D[ScalarT: np.generic] = np.ndarray[tuple[int], np.dtype[ScalarT]]
type _Array2D[ScalarT: np.generic] = np.ndarray[tuple[int, int], np.dtype[ScalarT]]
type _Sequence2D[T] = Sequence[Sequence[T]]

type _inexact32 = np.complex64 | np.float32
type _inexact64 = np.complex128 | np.float64

###

# keep in sync with `log`, `log10`, `log2`, `arccos`
@overload  # Nd T@complexfloating
def sqrt[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def sqrt[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | np.integer | np.bool]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def sqrt[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def sqrt[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def sqrt(x: float | np.integer | np.bool) -> _inexact64: ...
@overload  # 0d ~f32
def sqrt(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def sqrt(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def sqrt[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def sqrt(x: Sequence[float | np.integer | np.bool]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def sqrt(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def sqrt(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def sqrt[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def sqrt(x: _Sequence2D[float | np.integer | np.bool]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def sqrt(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def sqrt(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def sqrt(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log10`, `log2`, `arccos`
@overload  # Nd T@complexfloating
def log[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def log[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | np.integer | np.bool]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def log[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def log[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def log(x: float | np.integer | np.bool) -> _inexact64: ...
@overload  # 0d ~f32
def log(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def log(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def log[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def log(x: Sequence[float | np.integer | np.bool]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def log(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def log(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def log[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def log(x: _Sequence2D[float | np.integer | np.bool]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def log(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def log(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def log(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log`, `log2`, `arccos`
@overload  # Nd T@complexfloating
def log10[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def log10[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | np.integer | np.bool]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def log10[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def log10[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def log10(x: float | np.integer | np.bool) -> _inexact64: ...
@overload  # 0d ~f32
def log10(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def log10(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def log10[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def log10(x: Sequence[float | np.integer | np.bool]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def log10(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def log10(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def log10[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def log10(x: _Sequence2D[float | np.integer | np.bool]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def log10(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def log10(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def log10(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log`, `log10`, `arccos`
@overload  # Nd T@complexfloating
def log2[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def log2[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | np.integer | np.bool]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def log2[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def log2[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def log2(x: float | np.integer | np.bool) -> _inexact64: ...
@overload  # 0d ~f32
def log2(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def log2(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def log2[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def log2(x: Sequence[float | np.integer | np.bool]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def log2(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def log2(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def log2[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def log2(x: _Sequence2D[float | np.integer | np.bool]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def log2(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def log2(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def log2(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

@overload
def logn(n: _FloatLike_co, x: _FloatLike_co) -> Any: ...
@overload
def logn(n: _ComplexLike_co, x: _ComplexLike_co) -> complexfloating: ...
@overload
def logn(n: _ArrayLikeFloat_co, x: _ArrayLikeFloat_co) -> NDArray[Any]: ...
@overload
def logn(n: _ArrayLikeComplex_co, x: _ArrayLikeComplex_co) -> NDArray[complexfloating]: ...

@overload
def power(x: _FloatLike_co, p: _FloatLike_co) -> Any: ...
@overload
def power(x: _ComplexLike_co, p: _ComplexLike_co) -> complexfloating: ...
@overload
def power(x: _ArrayLikeFloat_co, p: _ArrayLikeFloat_co) -> NDArray[Any]: ...
@overload
def power(x: _ArrayLikeComplex_co, p: _ArrayLikeComplex_co) -> NDArray[complexfloating]: ...

# keep in sync with `sqrt`, `log`, `log10`, `log2`
@overload  # Nd T@complexfloating
def arccos[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def arccos[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | np.integer | np.bool]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def arccos[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def arccos[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def arccos(x: float | np.integer | np.bool) -> _inexact64: ...
@overload  # 0d ~f32
def arccos(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def arccos(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def arccos[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def arccos(x: Sequence[float | np.integer | np.bool]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def arccos(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def arccos(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def arccos[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def arccos(x: _Sequence2D[float | np.integer | np.bool]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def arccos(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def arccos(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def arccos(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

@overload
def arcsin(x: _FloatLike_co) -> Any: ...
@overload
def arcsin(x: _ComplexLike_co) -> complexfloating: ...
@overload
def arcsin(x: _ArrayLikeFloat_co) -> NDArray[Any]: ...
@overload
def arcsin(x: _ArrayLikeComplex_co) -> NDArray[complexfloating]: ...

@overload
def arctanh(x: _FloatLike_co) -> Any: ...
@overload
def arctanh(x: _ComplexLike_co) -> complexfloating: ...
@overload
def arctanh(x: _ArrayLikeFloat_co) -> NDArray[Any]: ...
@overload
def arctanh(x: _ArrayLikeComplex_co) -> NDArray[complexfloating]: ...
