from collections.abc import Sequence
from typing import Any, overload

import numpy as np
from numpy._typing import NDArray, _ArrayLikeComplex_co, _ComplexLike_co, _Shape

__all__ = ["sqrt", "log", "log2", "logn", "log10", "power", "arccos", "arcsin", "arctanh"]

###

type _Array1D[ScalarT: np.generic] = np.ndarray[tuple[int], np.dtype[ScalarT]]
type _Array2D[ScalarT: np.generic] = np.ndarray[tuple[int, int], np.dtype[ScalarT]]

type _Sequence2D[T] = Sequence[Sequence[T]]
type _SequenceMax2D[T] = T | Sequence[T] | Sequence[Sequence[T]]

type _inexact32 = np.complex64 | np.float32
type _inexact64 = np.complex128 | np.float64

type _ToInt64 = np.integer | np.bool
type _ToFloat64 = float | _ToInt64
type _ToComplex128 = complex | np.complex64 | np.float32 | np.float16 | _ToInt64

###

# keep in sync with `log`, `log10`, `log2`, `arccos`, `arcsin`, `arctanh`
@overload  # Nd T@complexfloating
def sqrt[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def sqrt[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | _ToInt64]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def sqrt[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def sqrt[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def sqrt(x: _ToFloat64) -> _inexact64: ...
@overload  # 0d ~f32
def sqrt(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def sqrt(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def sqrt[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def sqrt(x: Sequence[_ToFloat64]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def sqrt(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def sqrt(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def sqrt[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def sqrt(x: _Sequence2D[_ToFloat64]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def sqrt(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def sqrt(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def sqrt(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log10`, `log2`, `arccos`, `arcsin`, `arctanh`
@overload  # Nd T@complexfloating
def log[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def log[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | _ToInt64]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def log[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def log[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def log(x: _ToFloat64) -> _inexact64: ...
@overload  # 0d ~f32
def log(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def log(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def log[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def log(x: Sequence[_ToFloat64]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def log(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def log(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def log[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def log(x: _Sequence2D[_ToFloat64]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def log(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def log(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def log(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log`, `log2`, `arccos`, `arcsin`, `arctanh`
@overload  # Nd T@complexfloating
def log10[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def log10[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | _ToInt64]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def log10[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def log10[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def log10(x: _ToFloat64) -> _inexact64: ...
@overload  # 0d ~f32
def log10(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def log10(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def log10[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def log10(x: Sequence[_ToFloat64]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def log10(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def log10(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def log10[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def log10(x: _Sequence2D[_ToFloat64]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def log10(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def log10(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def log10(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log`, `log10`, `arccos`, `arcsin`, `arctanh`
@overload  # Nd T@complexfloating
def log2[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def log2[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | _ToInt64]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def log2[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def log2[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def log2(x: _ToFloat64) -> _inexact64: ...
@overload  # 0d ~f32
def log2(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def log2(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def log2[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def log2(x: Sequence[_ToFloat64]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def log2(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def log2(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def log2[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def log2(x: _Sequence2D[_ToFloat64]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def log2(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def log2(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def log2(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

#
@overload  # Nd ~c128
def logn[ShapeT: _Shape](
    n: _ToComplex128,
    x: np.ndarray[ShapeT, np.dtype[np.complex128]],
) -> np.ndarray[ShapeT, np.dtype[np.complex128]]: ...
@overload  # Nd +f64
def logn[ShapeT: _Shape](
    n: _ToFloat64,
    x: np.ndarray[ShapeT, np.dtype[np.float64 | np.float32 | _ToInt64]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def logn[ShapeT: _Shape](
    n: np.float32,
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # Nd +complex  (fallback)
def logn[ShapeT: _Shape](
    n: complex,
    x: np.ndarray[ShapeT, np.dtype[np.number | np.bool]],
) -> np.ndarray[ShapeT, np.dtype[np.complex128 | Any]]: ...
@overload  # 0d ~c128
def logn(n: _ToComplex128, x: np.complex128) -> np.complex128: ...
@overload  # 0d +f64
def logn(n: _ToFloat64, x: _ToFloat64 | np.float32) -> _inexact64: ...
@overload  # 0d ~f32
def logn(n: np.float32, x: np.float32) -> _inexact32: ...
@overload  # 0d +complex  (fallback)
def logn(n: complex, x: complex) -> np.complex128 | Any: ...
@overload  # 1d ~c128
def logn(n: _ToComplex128, x: Sequence[np.complex128]) -> _Array1D[np.complex128]: ...
@overload  # 1d +f64
def logn(n: _ToFloat64, x: Sequence[_ToFloat64 | np.float32]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def logn(n: np.float32, x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d +complex  (fallback)
def logn(n: complex, x: Sequence[_ComplexLike_co]) -> _Array1D[np.complex128 | Any]: ...
@overload  # 2d ~c128
def logn(n: _ToComplex128, x: _Sequence2D[np.complex128]) -> _Array2D[np.complex128]: ...
@overload  # 2d +f64
def logn(n: _ToFloat64, x: _Sequence2D[_ToFloat64 | np.float32]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def logn(n: np.float32, x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d +complex  (fallback)
def logn(n: complex, x: _Sequence2D[_ComplexLike_co]) -> _Array2D[np.complex128 | Any]: ...
@overload  # ?d  (fallback)
def logn(n: _ArrayLikeComplex_co, x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

#
@overload  # Nd ~c128
def power[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.complex128]],
    p: _ToComplex128,
) -> np.ndarray[ShapeT, np.dtype[np.complex128]]: ...
@overload  # Nd +f64
def power[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | np.float32]],
    p: _ToFloat64,
) -> np.ndarray[ShapeT, np.dtype[_inexact64 | Any]]: ...
@overload  # Nd ~f32
def power[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
    p: np.float32,
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # Nd +i64
def power[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.signedinteger | np.bool]],
    p: _ToFloat64,
) -> np.ndarray[ShapeT, np.dtype[_inexact64 | np.int64]]: ...
@overload  # 0d ~c128
def power(x: np.complex128, p: _ToComplex128) -> np.complex128: ...
@overload  # 0d +f64
def power(x: float | np.float32, p: _ToFloat64) -> _inexact64 | Any: ...
@overload  # 0d ~f32
def power(x: np.float32, p: np.float32) -> _inexact32: ...
@overload  # 0d +i64
def power(x: np.signedinteger | np.bool, p: _ToFloat64) -> _inexact64 | np.int64: ...
@overload  # 0d +complex  (fallback)
def power(x: _ComplexLike_co, p: _ComplexLike_co) -> np.complex128 | Any: ...
@overload  # 1d ~c128
def power(x: Sequence[np.complex128], p: _ToComplex128 | Sequence[_ToComplex128]) -> _Array1D[np.complex128]: ...
@overload  # 1d +f64
def power(x: Sequence[float | np.float32], p: _ToFloat64 | Sequence[_ToFloat64]) -> _Array1D[_inexact64 | Any]: ...
@overload  # 1d ~f32
def power(x: Sequence[np.float32], p: np.float32 | Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d +i64
def power(x: Sequence[np.signedinteger | np.bool], p: _ToFloat64 | Sequence[_ToFloat64]) -> _Array1D[_inexact64 | np.int64]: ...
@overload  # 1d +complex  (fallback)
def power(x: Sequence[_ComplexLike_co], p: _ComplexLike_co | Sequence[_ComplexLike_co]) -> _Array1D[np.complex128 | Any]: ...
@overload  # 2d ~c128
def power(x: _Sequence2D[np.complex128], p: _SequenceMax2D[_ToComplex128]) -> _Array2D[np.complex128]: ...
@overload  # 2d +f64
def power(x: _Sequence2D[float | np.float32], p: _SequenceMax2D[_ToFloat64]) -> _Array2D[_inexact64 | Any]: ...
@overload  # 2d ~f32
def power(x: _Sequence2D[np.float32], p: _SequenceMax2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d +i64
def power(x: _Sequence2D[np.signedinteger | np.bool], p: _SequenceMax2D[_ToFloat64]) -> _Array2D[_inexact64 | np.int64]: ...
@overload  # 2d +complex  (fallback)
def power(x: _Sequence2D[_ComplexLike_co], p: _SequenceMax2D[_ComplexLike_co]) -> _Array2D[np.complex128 | Any]: ...
@overload  # ?d  (fallback)
def power(x: _ArrayLikeComplex_co, p: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log`, `log10`, `log2`, `arcsin`, `arctanh`
@overload  # Nd T@complexfloating
def arccos[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def arccos[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | _ToInt64]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def arccos[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def arccos[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def arccos(x: _ToFloat64) -> _inexact64: ...
@overload  # 0d ~f32
def arccos(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def arccos(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def arccos[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def arccos(x: Sequence[_ToFloat64]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def arccos(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def arccos(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def arccos[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def arccos(x: _Sequence2D[_ToFloat64]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def arccos(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def arccos(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def arccos(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log`, `log10`, `log2`, `arccos`, `arctanh`
@overload  # Nd T@complexfloating
def arcsin[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def arcsin[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | _ToInt64]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def arcsin[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def arcsin[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def arcsin(x: _ToFloat64) -> _inexact64: ...
@overload  # 0d ~f32
def arcsin(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def arcsin(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def arcsin[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def arcsin(x: Sequence[_ToFloat64]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def arcsin(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def arcsin(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def arcsin[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def arcsin(x: _Sequence2D[_ToFloat64]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def arcsin(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def arcsin(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def arcsin(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...

# keep in sync with `sqrt`, `log`, `log10`, `log2`, `arccos`, `arcsin`
@overload  # Nd T@complexfloating
def arctanh[ShapeT: _Shape, ComplexT: np.complex128 | np.complex64](
    x: np.ndarray[ShapeT, np.dtype[ComplexT]],
) -> np.ndarray[ShapeT, np.dtype[ComplexT]]: ...
@overload  # Nd ~f64
def arctanh[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float64 | _ToInt64]],
) -> np.ndarray[ShapeT, np.dtype[_inexact64]]: ...
@overload  # Nd ~f32
def arctanh[ShapeT: _Shape](
    x: np.ndarray[ShapeT, np.dtype[np.float32]],
) -> np.ndarray[ShapeT, np.dtype[_inexact32]]: ...
@overload  # 0d T@complexfloating
def arctanh[ComplexT: np.complex128 | np.complex64](x: ComplexT) -> ComplexT: ...
@overload  # 0d ~f64
def arctanh(x: _ToFloat64) -> _inexact64: ...
@overload  # 0d ~f32
def arctanh(x: np.float32) -> _inexact32: ...
@overload  # 0d ~complex
def arctanh(x: complex) -> np.complex128 | Any: ...
@overload  # 1d T@complexfloating
def arctanh[ComplexT: np.complex128 | np.complex64](x: Sequence[ComplexT]) -> _Array1D[ComplexT]: ...
@overload  # 1d ~f64
def arctanh(x: Sequence[_ToFloat64]) -> _Array1D[_inexact64]: ...
@overload  # 1d ~f32
def arctanh(x: Sequence[np.float32]) -> _Array1D[_inexact32]: ...
@overload  # 1d ~complex
def arctanh(x: list[complex]) -> _Array1D[np.complex128]: ...
@overload  # 2d T@complexfloating
def arctanh[ComplexT: np.complex128 | np.complex64](x: _Sequence2D[ComplexT]) -> _Array2D[ComplexT]: ...
@overload  # 2d ~f64
def arctanh(x: _Sequence2D[_ToFloat64]) -> _Array2D[_inexact64]: ...
@overload  # 2d ~f32
def arctanh(x: _Sequence2D[np.float32]) -> _Array2D[_inexact32]: ...
@overload  # 2d ~complex
def arctanh(x: Sequence[list[complex]]) -> _Array2D[np.complex128]: ...
@overload  # ?d  (fallback)
def arctanh(x: _ArrayLikeComplex_co) -> NDArray[Any] | Any: ...
