from typing import Any, List

__all__: List[str]

class NumpyVersion:
    vstring: Any
    version: Any
    major: Any
    minor: Any
    bugfix: Any
    pre_release: Any
    is_devversion: Any
    def __init__(self, vstring): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
