# Last Change: Tue May 20 05:00 PM 2008 J
# vim:syntax=python
from numscons import GetNumpyEnvironment, scons_get_paths

env = GetNumpyEnvironment(ARGUMENTS)
env.Append(CPPPATH = scons_get_paths(env['include_bootstrap']))

_compiled_base = env.NumpyPythonExtension('_compiled_base', 
                                        source = ['src/_compiled_base.c'])
