# Last Change: Thu Jun 12 06:00 PM 2008 J
# vim:syntax=python
from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)
env.Prepend(CPPPATH=["#$build_prefix/numpy/core/src/private"])
env.NumpyPythonExtension('_compiled_base', source = ['src/_compiled_base.c'])
