from typing import Any, List

__all__: List[str]

class DummyArray:
    __array_interface__: Any
    base: Any
    def __init__(self, interface, base=...): ...

def as_strided(x, shape=..., strides=..., subok=..., writeable=...): ...
def sliding_window_view(x, window_shape, axis=..., *, subok=..., writeable=...): ...
def broadcast_to(array, shape, subok=...): ...
def broadcast_shapes(*args): ...
def broadcast_arrays(*args, subok=...): ...
