from typing import List

from numpy.core.numerictypes import (
    issubclass_ as issubclass_,
    issubdtype as issubdtype,
    issubsctype as issubsctype,
)

__all__: List[str]

def get_include(): ...
def deprecate(*args, **kwargs): ...
def deprecate_with_doc(msg): ...
def byte_bounds(a): ...
def who(vardict=...): ...
def info(object=..., maxwidth=..., output=..., toplevel=...): ...
def source(object, output=...): ...
def lookfor(what, module=..., import_modules=..., regenerate=..., output=...): ...
def safe_eval(source): ...
