#!/bin/sh

f2py2e=../../f2py2e.py

$f2py2e com1.f -m com1 -h com1.pyf --overwrite-signature --overwrite-makefile
gmake -f Makefile-com1 clean com1

$f2py2e com1.f -m com2 -h com2.pyf --overwrite-signature --overwrite-makefile
gmake -f Makefile-com2 clean com2

python -c '
import com1,Numeric
import com2
print com1.__doc__
print "Common block anodata in com1:"
print com1.anodata.__doc__
print "Common block c12data3 in com1:"
print com1.c12data3.__doc__
print "Settign /c12data3/ = [56],23"
com1.c12data3.i=[56]
com1.c12data3.j=23
print "Calling com1.foo():"
com1.foo()
print "Calling com1.bar():"
com1.bar()
print "Calling com2.bar():"
com2.bar()
print "com1.anodata.r.shape=",com1.anodata.r.shape
print "Setting r=[[1,2,3],[4,5,6]]"
com1.anodata.r=[[1,2,3],[4,5,6]]
print "The result is"
print com1.anodata.r
com1.anodata.r[0]=2000000
print "The result is"
print com1.anodata.r

print "Calling com1.bar():"
com1.bar()
print "Setting r=transpose([[1,2],[3,4],[5,6]])"
com1.anodata.r=Numeric.transpose([[1,2],[3,4],[5,6]])
print "Calling com1.bar():"
com1.bar()
print "The transposed result is"
print Numeric.transpose(com1.anodata.r)
print "ok"
'
