# Temporary file for musl dev builds
# TODO: Remove file before merge
FROM python:3.10-alpine

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN apk add git build-base \
    && pip install virtualenv
COPY . /numpy
WORKDIR /numpy
RUN python -m build \
    && python -m virtualenv /venv \
    && source /venv/bin/activate \
    && pip install -r test_requirements.txt \
    && pip install dist/numpy*.whl \
    && apk del git build-base    


# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["python", "runtests.py", "-v", "-n"]
