[package.build]
source.path = "../.."
flags = ["asan"]

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.config]
extra-input-globs = ["**/*.c.src"]
compilers = ["c", "cxx"]
env.ASAN_OPTIONS = "detect_leaks=0:symbolize=1:strict_init_order=true:allocator_may_return_null=1:use_sigaltstack=0"
extra-args = ["-Csetup-args=-Db_sanitize=address", "-Csetup-args=-Dbuildtype=debug"] 

[package.host-dependencies]
python.flags = ["asan"]
python.git = "https://github.com/python/cpython"
python.subdirectory = "Tools/pixi-packages"
python.rev = "abdd7aea18bde039fe35983b5c0d8036bc16f1a7"

meson-python = "*"
cython = "*"
