[package.build]
source.path = "../.."
flags = ["asan"]

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.config]
extra-input-globs = ["**/*.c.src"]
compilers = ["c", "cxx"]
env.ASAN_OPTIONS = "detect_leaks=0:symbolize=1:strict_init_order=true:allocator_may_return_null=1:use_sigaltstack=0"
extra-args = ["-Csetup-args=-Db_sanitize=address", "-Csetup-args=-Dbuildtype=debug"] 

[package.host-dependencies]
python = {
  flags = ["asan"],
  git = "https://github.com/lucascolley/cpython",
  subdirectory = "Tools/pixi-packages",
  rev = "aa372d05e1e6ab3f1b16f4e13841b347f5b37e89",
}
meson-python = "*"
cython = "*"
