[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
preview = ["pixi-build"]
requires-pixi = ">=0.71.2"

[package.build]
source.path = "../.."
flags = ["asan"]

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.config]
extra-input-globs = ["**/*.c.src"]
compilers = ["c", "cxx"]
env.ASAN_OPTIONS = "detect_leaks=0:symbolize=1:strict_init_order=true:allocator_may_return_null=1:use_sigaltstack=0"
extra-args = ["-Csetup-args=-Db_sanitize=address", "-Csetup-args=-Dbuildtype=debug"] 

[package.host-dependencies]
python.flags = ["asan"]
python.git = "https://github.com/lucascolley/cpython"
python.subdirectory = "Tools/pixi-packages"
python.rev = "8b5b0c29797cf88d78ef014916a5e5a5d51bbf95"

python_abi.git = "https://github.com/lucascolley/cpython"
python_abi.subdirectory = "Tools/pixi-packages"
python_abi.rev = "8b5b0c29797cf88d78ef014916a5e5a5d51bbf95"

meson-python = "*"
cython = "*"
