# vim:syntax=python
from numpy.distutils.scons import GetNumpyEnvironment, NumpyCheckLib

env = GetNumpyEnvironment(ARGUMENTS)

config = env.NumpyConfigure(custom_tests = {'NumpyCheckLib' : NumpyCheckLib})
if not config.NumpyCheckLib('sndfile', 'sf_open', section = 'sndfile'):
    print "sndfile not found, this package cannot work without sndfile !"
config.Finish()
