name: Test on Cygwin
on:
  push:
    branches:
      - master
      - add-cygwin-build-to-ci
  pull_request:
    branches:
      - master
jobs:
  cygwin_build_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          install-dir: 'C:\tools\cygwin'
          packages: python38-devel python38-pytest python38-hypothesis python38-cython python38-pip python38-wheel python38-setuptools liblapack-devel libopenblas gcc-fortran git
      - name: Set Windows PATH
        uses: egor-tensin/cleanup-path@v1
        with:
          dirs: 'C:\tools\cygwin\bin'
      - name: Verify that bash is Cygwin bash
        run: |
          command bash
          bash -c "uname -svrmo"
      - name: Update with Cygwin git
        # fetch-depth=0 above should make this short.
        run: |
          bash -c "type git; git fetch --all -p"
      - name: Verify python version
        # Make sure it's the Cygwin one, not a Windows one
        run: |
          bash -c "type python3.8; python3.8 --version -V"
      - name: Build NumPy wheel
        run: |
          bash -c "python3.8 setup.py bdist_wheel"
      - name: Install new NumPy
        run: |
          bash -c "python3.8 -m pip install dist/numpy-*cp38*.whl"
      - name: Run NumPy test suite
        run: |
          bash -c "mkdir empty"
          bash -c "cd empty && python3.8 -c 'import numpy as np; np.test()' && cd .."
