name: iOS tests

on:
  pull_request:
    branches:
      - main
      - maintenance/**
    paths-ignore:
      - '**.pyi'
      - '**.md'
      - '**.rst'

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-ios:
    permissions:
      contents: read  # to fetch code (actions/checkout)
    name: Test (${{ matrix.arch }} ${{ matrix.accelerated && 'accelerated' || 'non-accelerated' }})
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Accelerated
          - runs-on: "macos-26"
            accelerated: true
            arch: arm64_iphoneos
          - runs-on: "macos-26"
            accelerated: true
            arch: arm64_iphonesimulator

          # Non-accelerated
          - runs-on: "macos-26"
            accelerated: false
            arch: arm64_iphoneos
          - runs-on: "macos-26"
            accelerated: false
            arch: arm64_iphonesimulator

    # To enable this workflow on a fork, comment out:
    if: github.repository == 'numpy/numpy'
    steps:
      - name: Checkout NumPy
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
          fetch-tags: true
          persist-credentials: false

      - name: Setup iOS
        run: |
          if ${{ matrix.accelerated }}; then
            # Accelerate with ILP64 requires iOS 16.4 or higher
            CIBW_ENV="IPHONEOS_DEPLOYMENT_TARGET=17.0"
            echo "CIBW_ENVIRONMENT_IOS=$CIBW_ENV" >> "$GITHUB_ENV"
          else
            # On older iOS versions, disable ILP64.
            CIBW_CONFIG="setup-args=-Duse-ilp64=false setup-args=-Dallow-noblas=true build-dir=build"
            echo "CIBW_CONFIG_IOS=$CIBW_CONFIG" >> "$GITHUB_ENV"
          fi

      - name: Build wheels
        uses: pypa/cibuildwheel@294735312765b09d24a2fbec22660ce817587d55  # v4.1.0
        env:
          CIBW_PLATFORM: ios
          CIBW_ARCHS: ${{ matrix.arch }}
