      ! gh-32360
      MODULE SIDE_A_MOD
      IMPLICIT NONE
      CONTAINS

      PURE REAL FUNCTION ADDONE(INVAR)
            REAL, INTENT(IN) :: INVAR
            ADDONE = INVAR + 1
      ENDFUNCTION ADDONE

      ENDMODULE SIDE_A_MOD
