      ! gh-32360
      MODULE SIDE_B_MOD
      IMPLICIT NONE
      CONTAINS

      PURE REAL FUNCTION ADDTWO(INVAR)
            REAL, INTENT(IN) :: INVAR
            ADDTWO = INVAR + 2
      ENDFUNCTION ADDTWO

      ENDMODULE SIDE_B_MOD
